server:
  port: 8080

spring:
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/gen/*.xml
  type-aliases-package: com.bingoabin.persistence.po.gen
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
